# -*- coding: utf-8 -*-
"""Examen Programación.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/dianamromeroc/0cb1a570aa2061eed648b7e118e14690/examen-programaci-n.ipynb
"""

from random import randrange

numeros = [3]

print(random.randint(1, 10))